add checks to verify that dependencies of respective script are installed

diff --git a/bash/crop b/bash/crop
--- a/bash/crop
+++ b/bash/crop
@@ -1,21 +1,29 @@
 #! /bin/sh
 
 if [ -z "$1" ] || [ "$1" = "-h" ]; then
-  echo "crop –– crop one or multiple images using imagemagick"
-  echo "usage: crop <image or pattern> <crop geometry> [optional output dir]"
-  echo ""
-  echo "examples:"
-  echo "- crop single image:"
-  echo "  crop my-image.png 779x436+550+120"
-  echo "- crop multiple images:"
-  echo "  crop \"*.png\" 779x436+550+120"
-  echo "- crop multiple images and put in 'cropped' folder:"
-  echo "  crop \"*.png\" 779x436+550+120 ./cropped"
-  echo ""
-  echo "how to read the 'crop geometry' (ie. 779x436+550+120):"
-  echo "from pixel 0x0 (top left of given picture), select area of"
-  echo "779px to right and 436px to bottom and then push the"
-  echo "selected area 550px to right and 120px to bottom"
+    echo "crop –– crop one or multiple images using imagemagick"
+    echo "usage: crop <image or pattern> <crop geometry> [optional output dir]"
+    echo ""
+    echo "examples:"
+    echo "- crop single image:"
+    echo "  crop my-image.png 779x436+550+120"
+    echo "- crop multiple images:"
+    echo "  crop \"*.png\" 779x436+550+120"
+    echo "- crop multiple images and put in 'cropped' folder:"
+    echo "  crop \"*.png\" 779x436+550+120 ./cropped"
+    echo ""
+    echo "how to read the 'crop geometry' (ie. 779x436+550+120):"
+    echo "from pixel 0x0 (top left of given picture), select area of"
+    echo "779px to right and 436px to bottom and then push the"
+    echo "selected area 550px to right and 120px to bottom"
+fi
+
+# verify dependencies
+hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
+if [ ! -z "$MISSING_DEPS" ]; then
+    echo "whoops! missing dependencies:"
+    echo $MISSING_DEPS
+    exit
 fi
 
 current_dir=$(pwd)
@@ -23,33 +31,33 @@ current_dir=$(pwd)
 crop_geometry=$2
 output_dir=$3
 for filename in $1; do
-  if [ ! -e "$filename" ]; then
-    echo "crop skipped: $filename does not exist"
-    break
-  fi
+    if [ ! -e "$filename" ]; then
+        echo "crop skipped: $filename does not exist"
+        break
+    fi
 
-  # if output dir is given, do not modify filename
-  if [ ! -z "$output_dir" ]; then
-    convert $filename -crop $crop_geometry $output_dir/$filename
-    echo "$filename → $output_dir/$filename"
-    continue
-  fi
+    # if output dir is given, do not modify filename
+    if [ ! -z "$output_dir" ]; then
+        convert $filename -crop $crop_geometry $output_dir/$filename
+        echo "$filename → $output_dir/$filename"
+        continue
+    fi
 
-  # ---
-  # output dir is not given. modify filename to become
-  # cropped__{filename} and put it in
-  # the same directory.
-  # ---
+    # ---
+    # output dir is not given. modify filename to become
+    # cropped__{filename} and put it in
+    # the same directory.
+    # ---
 
-  dir_name=$(dirname "$filename")
+    dir_name=$(dirname "$filename")
 
-  # get filename with extension
-  filename_with_ext=$(basename "$filename")
+    # get filename with extension
+    filename_with_ext=$(basename "$filename")
 
-  # extract extension
-  ext="${filename_with_ext##*.}"
+    # extract extension
+    ext="${filename_with_ext##*.}"
 
-  cropped_file=cropped--$filename
-  convert $filename -crop $crop_geometry $dir_name/$cropped_file
-  echo "$filename → $cropped_file"
+    cropped_file=cropped--$filename
+    convert $filename -crop $crop_geometry $dir_name/$cropped_file
+    echo "$filename → $cropped_file"
 done
diff --git a/bash/diffy b/bash/diffy
--- a/bash/diffy
+++ b/bash/diffy
@@ -5,6 +5,15 @@
 # 2. copy or link this file to your path (ie. `ln -s diffy /usr/local/bin`)
 # 3. run diffy to upload your `git diff` to diffy
 
+# verify dependencies
+hash git 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS git"; }
+hash curl 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS curl"; }
+if [ ! -z "$MISSING_DEPS" ]; then
+    echo "whoops! missing dependencies:"
+    echo $MISSING_DEPS
+    exit
+fi
+
 if git rev-parse --git-dir > /dev/null 2>&1; then
     DIFF_FILE=/tmp/to_diffy.diff
     DIFF_COMMAND="git diff"
diff --git a/bash/dockerd-expose b/bash/dockerd-expose
--- a/bash/dockerd-expose
+++ b/bash/dockerd-expose
@@ -16,17 +16,30 @@ if [ -z "$PORT" ]; then
 	PORT=2375
 fi
 
-echo "docker will be accessible at port :${PORT}."
+# verify dependencies
+hash dsocat 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS socat"; }
+if [ ! -z "$MISSING_DEPS" ]; then
+    echo "whoops! missing dependencies:"
+    echo $MISSING_DEPS
+    exit
+fi
+
+echo "==========================================================="
+echo "docker engine will be accessible at port :${PORT}."
+echo "you'll need to have permission to"
+echo "/var/run/docker.sock to do this operation."
 echo "keep in mind that the connection is not secure (no tls)."
-echo "make sure you have permission to /var/run/docker.sock"
+echo "anyone in your network might be able to connect to this"
+echo "docker engine. handle with care."
+echo "==========================================================="
 echo ""
 echo "from your remote machine, use nmap to check"
 echo "if it can access this docker instance:"
-echo "nmap <ip of this machine> -p ${PORT}"
+echo "\`nmap <ip of this machine> -p ${PORT}\`"
 echo ""
-echo "then use 'DOCKER_HOST' to connect your"
+echo "then use 'DOCKER_HOST' env var to connect your"
 echo "remote docker client to this docker instance:"
-echo "DOCKER_HOST=<ip of this machine>:${PORT} docker info"
+echo "\`DOCKER_HOST=<ip of this machine>:${PORT} docker info\`"
 echo ""
 echo "to stop, press ctrl+c"
 
diff --git a/bash/ocr b/bash/ocr
--- a/bash/ocr
+++ b/bash/ocr
@@ -31,6 +31,15 @@ if [ -z "$1" ] || [ "$1" = "-h" ] || [ -z "$2" ]; then
     exit
 fi
 
+# verify dependencies
+hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
+hash tesseract 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS tesseract"; }
+if [ ! -z "$MISSING_DEPS" ]; then
+    echo "whoops! missing dependencies:"
+    echo $MISSING_DEPS
+    exit
+fi
+
 # handle directory
 if [ -d "$1" ] ; then
     for file in "$1"/*.{jpg,jpeg,png} ; do
diff --git a/bash/ytmp3 b/bash/ytmp3
--- a/bash/ytmp3
+++ b/bash/ytmp3
@@ -31,6 +31,15 @@ if [[ "$OUTPUT_DIR" != */ ]]; then
     OUTPUT_DIR="${OUTPUT_DIR}/"
 fi
 
+# verify dependencies
+hash ytdl 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ytdl"; }
+hash ffmpeg 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ffmpeg"; }
+if [ ! -z "$MISSING_DEPS" ]; then
+    echo "whoops! missing dependencies:"
+    echo $MISSING_DEPS
+    exit
+fi
+
 # use ytdl to fetch video info.
 # using ytdl v0.5.0, the info would look like this:
 # ```
