- change shell to bash due to usage of string substition - re-arrange code path for better readability

diff --git a/bash/diffy b/bash/diffy
--- a/bash/diffy
+++ b/bash/diffy
@@ -1,9 +1,14 @@
-#!/usr/bin/env sh
+#!/bin/bash
 
 # usage:
 # 1. adjust file permission (if you have not): `chmod +x diffy`
 # 2. copy or link this file to your path (ie. `ln -s diffy /usr/local/bin`)
 # 3. run diffy to upload your `git diff` to diffy
+if [ "$1" = "-h" ]; then
+    echo "diffy –– upload output of git diff to diffy.org"
+    echo "usage: diffy <git diff command (optional)>"
+    exit
+fi
 
 # verify dependencies
 hash git 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS git"; }
@@ -14,28 +19,29 @@ if [ ! -z "$MISSING_DEPS" ]; then
     exit
 fi
 
-if git rev-parse --git-dir > /dev/null 2>&1; then
-    DIFF_FILE=/tmp/to_diffy.diff
-    DIFF_COMMAND="git diff"
-    if [ -z "$1" ]; then
-        `$DIFF_COMMAND > $DIFF_FILE`
-    elif [ $1 == "-h" ]; then
-        echo "diffy –– upload output of git diff to diffy.org"
-        echo "usage: diffy <git diff command (optional)>"
-        exit
-    else
-        DIFF_COMMAND=$@
-        `$DIFF_COMMAND > $DIFF_FILE`
-    fi
-
-    echo "uploading output of '$DIFF_COMMAND' to diffy.org.."
-
-    # sample response:
-    # Found. Redirecting to /diff/4hrag1lvv7lgyt81v6t0fqolxr
-    diffy_response=`curl -s -F diffFile=@$DIFF_FILE https://diffy.org/new`
-
-    replacer=diffy.org/diff
-    echo "${diffy_response/\/diff/$replacer}"
-else
-    echo "diffy error: this directory is not a git repo"
+# ensure current dir is git repo
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+    echo "diffy error: directory is not git repo"
+    exit
 fi
+
+# store output of `git diff` to DIFF_FILE
+DIFF_FILE=/tmp/to_diffy.diff
+DIFF_COMMAND="git diff"
+if [ -z "$1" ]; then
+    `$DIFF_COMMAND > $DIFF_FILE`
+else
+    DIFF_COMMAND=$@
+    `$DIFF_COMMAND > $DIFF_FILE`
+fi
+
+echo "uploading output of '$DIFF_COMMAND' to diffy.org.."
+
+# sample response:
+# Found. Redirecting to /diff/4hrag1lvv7lgyt81v6t0fqolxr
+diffy_response=`curl -s -F diffFile=@$DIFF_FILE https://diffy.org/new`
+
+# shell won't understand below string substition. 
+# use bash instead.
+replacer=https\://diffy.org/diff
+echo "${diffy_response/\/diff/$replacer}"
