chore(ytmp3): swap arg position. use current dir as default output dir.

diff --git a/bash/ytmp3 b/bash/ytmp3
--- a/bash/ytmp3
+++ b/bash/ytmp3
@@ -11,23 +11,25 @@
 # - awk: https://www.gnu.org/software/gawk/manual/gawk.html
 
 # display usage info
-if [ "$1" == "-h" ] || [ -z "$1" ] || [ -z "$2" ]; then
+if [ "$1" == "-h" ] || [ -z "$1" ]; then
     echo "ytmp3 –– download youtube video and convert to mp3"
-    echo "usage: ytmp3 <output dir> <youtube video id>"
-    echo "example: ytmp3 ~/Downloads/ RXARHZmpgvw"
+    echo "usage: ytmp3 <youtube url/video id> <output dir>"
+    echo "example:"
+    echo "- ytmp3 RXARHZmpgvw ~/Downloads/"
+    echo "- ytmp3 https://www.youtube.com/watch?v=p29JUpsOSTE ~/Downloads/"
     exit
 fi
 
 # ensure output dir exists
-OUTPUT_DIR=$1
-if [ ! -d "$OUTPUT_DIR" ]; then
-    echo "Error: directory '$1' doesn't exist."
+OUTPUT_DIR=$2
+if [ "$OUTPUT_DIR" != "" ] && [ ! -d "$OUTPUT_DIR" ]; then
+    echo "Error: directory '$2' doesn't exist."
     echo "Please create the directory and try again."
-    exit
+    exit 1
 fi
 
 # ensure output dir has / suffix
-if [[ "$OUTPUT_DIR" != */ ]]; then
+if [ "$OUTPUT_DIR" != "" ] && [[ "$OUTPUT_DIR" != */ ]]; then
     OUTPUT_DIR="${OUTPUT_DIR}/"
 fi
 
@@ -37,7 +39,7 @@ hash ffmpeg 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ffmpeg"; }
 if [ ! -z "$MISSING_DEPS" ]; then
     echo "whoops! missing dependencies:"
     echo $MISSING_DEPS
-    exit
+    exit 2
 fi
 
 # use ytdl to fetch video info.
@@ -52,25 +54,27 @@ fi
 # the `awk -F': ' 'NR == 1 {print $2}'` will get the first
 # line of video info ('NR == 1'), and take the part of
 # line that comes after ': ' (-F': ').
-FILENAME=`ytdl --info $2 | awk -F': ' 'NR == 1 {print $2}'`
+FILENAME=`ytdl --info $1 | awk -F': ' 'NR == 1 {print $2}'`
 if [ -z "$FILENAME" ]; then
-    echo "Download failed: video id '$2' is invalid"
-    exit
+    echo "Download failed: video id '$1' is invalid"
+    exit 3
 fi
 
 echo "Downloading: $FILENAME"
-ytdl --filter best-audio --output $OUTPUT_DIR{{.Title}}.{{.Ext}} $2
+ytdl --filter best-audio --output $OUTPUT_DIR{{.Title}}.{{.Ext}} $1
 
 # ensure the video is downloaded
-if [ ! -f "${OUTPUT_DIR}${FILENAME}.webm" ]; then
+video_file="${OUTPUT_DIR}${FILENAME}.webm"
+if [ ! -f "$video_file" ]; then
     echo "Error: Couldn't convert video to mp3. Video file doesn't exist."
-    exit
+    exit 4
 fi
 
 echo "Converting to mp3.."
-ffmpeg -loglevel 0 -hide_banner -nostats -i "${OUTPUT_DIR}${FILENAME}.webm" "${OUTPUT_DIR}${FILENAME}.mp3"
+mp3_file=${OUTPUT_DIR}${FILENAME}.mp3
+ffmpeg -loglevel 0 -hide_banner -nostats -i "${OUTPUT_DIR}${FILENAME}.webm" "$mp3_file"
 
 echo "Deleting webm file.."
 rm "${OUTPUT_DIR}${FILENAME}.webm"
 
-echo "✔ ytmp3 finished for '$2'"
+echo "✔ ytmp3 finished: ${mp3_file}"
